### ISSUE TITLE
Would you bump a version to v.1.11 and make a release?

### ISSUE THREAD

**Issue by yoku0825** [innotop/innotop#138]
I seem innotop supports MySQL 5.7 around #137 and #135 .
That works well in my environments, 5.7.10, 5.7.11 and 5.7.12.

How about bumping a version into v.1.11 at now?

**Comment by yoku0825** [comment]
And making release is helpful for my rpmbuild.

**Comment by grypyrg** [comment]
👍 @lefred Do you think you have some spare time to make a new release and maybe upload rpm/deb packages here in github?
I'm very loaded on work atm. and have vacation coming up.

**Comment by ari** [comment]
+1 for this. The FreeBSD packages are three years out of date [1] mainly because there isn't a release to track against. Even a source code release bundle here would help me to update the FreeBSD port to something that works better (lots of things are broken in that old release).

Also, you might want to review the top level Changelog file or remove it. At first I thought this project had been abandoned.

[1] https://www.freshports.org/databases/innotop/

**Comment by lefred** [comment]
A new tag and a new release has been made.
Enjoy

**Comment by yoku0825** [comment]
Thank you!!

**Comment by ari** [comment]
FreeBSD packaging ticket made. If the maintainer doesn't pick it up soon, I'll sort it out.

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=210269

**Comment by yoku0825** [comment]
I sent a request to epel.

https://bugzilla.redhat.com/show_bug.cgi?id=1346187
