### ISSUE TITLE
Slave SQL and I/O does not show CXN or Channel info

### ISSUE THREAD

**Issue by Harmit** [innotop/innotop#150]
Starting with `innotop --mode M` or using default "innotop" and selecting the "M" option formats the Slave SQL Status table and the Slave I/O Status tables correctly, but leaves the column "CXN" and "Channel" blank.

Tested this on several CentOS 6 & 7 installations including source.

General OS and Package info:
```
OS: CentOS Linux release 7.2.1511 (Core) 
# uname -sro 
Linux 3.10.0-327.28.3.el7.x86_64 GNU/Linux

Yum Installed:
perl-TermReadKey-2.30-20.el7.x86_64
perl-Term-ReadLine-Gnu-1.26-2.el7.x86_64
innotop-1.11.1-1.el7.noarch
```

**Comment by sjalilund** [comment]
Tested this with the latest stable release from the repo (1.11.1), and can't reproduce.. 

<pre>
# uname -sro
Linux 3.10.0-327.18.2.el7.x86_64 GNU/Linux
# cat /etc/redhat-release
CentOS Linux release 7.2.1511 (Core) 
# git log |head
commit 0d64c78264818a1e56772bb9425ab1177325ffb9
Author: Frederic Descamps <lefred.descamps@gmail.com>
Date:   Tue Jun 14 13:56:00 2016 +0200
# git status
# On branch master
nothing to commit, working directory clean
Yum installed:
perl-Term-ReadLine-Gnu.x86_64        1.26-2.el7              centos7-epel-x86_64
</pre>

![innotop-5 7](https://cloud.githubusercontent.com/assets/18281400/21841910/a17f03b4-d7e4-11e6-855b-db18574a383e.png)

Tested on a CentOS 7.2.1511 with MySQL 5.6, and here, the Channel-column 
isn't populated, correctly, since 5.6 don't have channels 

![innotop-5 6](https://cloud.githubusercontent.com/assets/18281400/21841909/a17d76d4-d7e4-11e6-846a-7943fb3f281c.png)

**Comment by sjalilund** [comment]
I stand corrected... Were able to reproduce the error, and have fixed it in the latest checkin on 'my' branch. Have created a pull-request as well.
